#!/bin/bash
# =============================================================================
# Disk prune — 2026-09-17. Re-audited today against scratch/DISK-PRUNE-PLAN-
# 2026-09-11.md (the Trash is already empty; sizes below are today's).
#
#   bash scratch/prune-2026-09-17.sh            # DRY RUN: prints what and how much
#   bash scratch/prune-2026-09-17.sh --go       # does tiers 1 + 2 (no sudo needed)
#   bash scratch/prune-2026-09-17.sh --go --sudo         # + pacman cache, coredumps
#   bash scratch/prune-2026-09-17.sh --go --flash-next   # + the shelved 177B MoE (96 GB)
#
# SAFE TO RUN WHILE THE CAMPAIGN IS MEASURING: everything here is `rm` of cold
# files under ionice/nice — no builds, no GPU, nothing the campaign reads. The
# KEEP guard below refuses any weight a serve script in use, the campaign, or a
# live llama-server names, whatever the lists say.
#
# NEVER TOUCHED, on purpose:
#   * docker VOLUMES — the stack is down, so Open WebUI's data volume (your
#     chats and users) counts as "unused" right now. The old plan's
#     `docker system prune -a --volumes` would have been a bad day.
#   * research artifacts (research/lowrank/**, weights/research-staging/**):
#     that tier is OFFLOAD-to-external-drive, not delete — GPU-hours live there,
#     and stage F reads the IQ2 pair + BF16 this week.
#   * ~/Documents/scu, ~/Documents/projects — coursework, not mine to judge.
# =============================================================================
set -uo pipefail
GO=0; SUDO=0; FLASH=0
for a in "$@"; do
  case "$a" in
    --go) GO=1 ;; --sudo) SUDO=1 ;; --flash-next) FLASH=1 ;;
    -h|--help) sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done
# PRUNE_OB / PRUNE_PROC exist for tests/test_uninstall.sh (a throwaway tree
# and a fake /proc); nothing else sets them.
OB="${PRUNE_OB:-/home/max/Documents/openbeast}"
PROC="${PRUNE_PROC:-/proc}"
W="$OB/weights"
TOTAL_KB=0
say() { printf '%s\n' "$*"; }

# ---- KEEP guard: weights something still needs --------------------------------
KEEP="$( {
  # the default, the last-started and the bootstrap serve scripts
  for s in "$OB"/scripts/serve-qwen38-27b-uncensored-mtp-q5.sh \
           "$OB/scripts/$(head -n1 "$OB/.run/serve-script" 2>/dev/null || echo none)" \
           "$OB"/scripts/serve-bootstrap.sh \
           "$OB"/scripts/serve-qwen-27b-q5.sh "$OB"/scripts/serve-qwen38-27b-uncensored-q5.sh; do
    [[ -f "$s" ]] && grep -ho '[A-Za-z0-9._-]*\.gguf' "$s"
  done
  # everything ANY campaign/research script names — a glob, not a list: the
  # next campaign_master4.sh must be covered the day it is written. This
  # script is left out: it names its own targets.
  for s in "$OB"/scratch/*.sh; do
    [[ "$(basename "$s")" == prune-2026-09-17.sh ]] && continue
    grep -ho '[A-Za-z0-9._-]*\.gguf' "$s" 2>/dev/null
  done
  # anything a live llama-server is serving. NOT /proc/<pid>/fd: llama.cpp
  # closes the weight's fd once it is loaded (only the mmap survives), so fd
  # never shows it. The command line (-m / --mmproj / -md …) always names it,
  # and /proc/<pid>/maps shows it while it is mmapped.
  for p in $(pgrep -x llama-server 2>/dev/null); do
    tr '\0' '\n' < "$PROC/$p/cmdline" 2>/dev/null | grep -o '[A-Za-z0-9._-]*\.gguf'
    grep -o '[A-Za-z0-9._-]*\.gguf' "$PROC/$p/maps" 2>/dev/null
  done
} | sort -u )"

kb_of() { ionice -c3 nice -n19 du -sk "$1" 2>/dev/null | awk '{print $1}'; }

rm_path() {                       # rm_path <path> <why>
  local p="$1" why="$2" kb base
  [[ -e "$p" || -L "$p" ]] || return 0
  base="$(basename "$p")"
  if [[ "$base" == *.gguf ]] && grep -qxF "$base" <<< "$KEEP"; then
    say "  KEEP   $p — still named by a serve script / the campaign / a live server"
    return 0
  fi
  kb="$(kb_of "$p")"; kb="${kb:-0}"
  TOTAL_KB=$((TOTAL_KB + kb))
  printf '  %-6s %6.1f GB  %s\n         %s\n' "$([[ $GO -eq 1 ]] && echo rm || echo would)" \
         "$(awk -v k="$kb" 'BEGIN{print k/1048576}')" "$p" "$why"
  [[ $GO -eq 1 ]] && ionice -c3 nice -n19 rm -rf -- "$p"
  return 0
}

say "== TIER 1 — caches and leftovers: re-created on demand, zero decisions =="
rm_path ~/.cache/uv        "uv package cache"
rm_path ~/.cache/pip       "pip cache"
rm_path ~/.cache/pypoetry  "poetry cache"
rm_path ~/Downloads/ubuntu-26.04-desktop-amd64.iso "an installer ISO"
# HF hub cache: old NLP-course models + a dataset. Qwen3.5-0.8B-Base stays —
# the E16 0.8B experiment is ACTIVE and may re-read it.
for d in ~/.cache/huggingface/hub/*; do
  case "$(basename "$d")" in
    models--Qwen--Qwen3.5-0.8B-Base|version.txt|.locks) ;;
    *) rm_path "$d" "HF hub cache (re-downloadable)" ;;
  esac
done
rm_path ~/.cache/huggingface/datasets "HF datasets cache — derived Arrow files from NLP coursework; regenerated by re-running the notebook that made them"
# The two feature worktrees: #61 and #62 were squash-merged; both trees are clean.
for wt in "$(dirname "$OB")/openbeast-artifact" "$(dirname "$OB")/openbeast-chat"; do
  if [[ -d "$wt" ]]; then
    if [[ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]]; then
      say "  KEEP   $wt — it has uncommitted changes"
    else
      kb="$(kb_of "$wt")"; TOTAL_KB=$((TOTAL_KB + ${kb:-0}))
      say "  $([[ $GO -eq 1 ]] && echo rm || echo would)   worktree $wt (squash-merged; branch itself is kept)"
      [[ $GO -eq 1 ]] && git -C "$OB" worktree remove "$wt"
    fi
  fi
done
say ""
say "  docker: build cache + images/containers from projects untouched for 90+ days"
say "          (NOT volumes, NOT open-webui/searxng — see the header)"
# NOT `docker image prune -a --filter until=…`: with the stack down (stop.sh
# runs `compose down`) no container references the pinned open-webui/searxng
# images, so -a would take them the day their digest turns 90 days old — and
# on an OFFLINE=true rig nothing can pull them back. Images are chosen one by
# one instead, and every repository docker-compose.yml names is skipped.
PINNED="$( { grep -E '^[[:space:]]*image:' "$OB/docker-compose.yml" 2>/dev/null \
             | sed -E 's/^[[:space:]]*image:[[:space:]]*//; s/@.*//; s/:[^/:]*$//'
           printf '%s\n' open-webui searxng; } | sort -u )"
_pinned() { local r="$1" p; while IFS= read -r p; do [[ -n "$p" && "$r" == *"$p"* ]] && return 0; done <<< "$PINNED"; return 1; }
CUTOFF=$(( $(date +%s) - 90 * 86400 ))
if [[ $GO -eq 1 ]]; then
  docker builder prune -af 2>/dev/null | tail -n1
  docker container prune -f --filter "until=2160h" 2>/dev/null | tail -n1
else
  docker system df 2>/dev/null | awk 'NR==1 || /Build Cache|Images/'
fi
docker image ls --no-trunc --format '{{.ID}}\t{{.Repository}}\t{{.CreatedAt}}' 2>/dev/null \
  | while IFS=$'\t' read -r id repo created; do
      [[ -n "$id" ]] || continue
      if _pinned "$repo"; then say "  KEEP   image $repo — docker-compose.yml pins it"; continue; fi
      ts="$(date -d "${created% *}" +%s 2>/dev/null)" || continue   # "… +0000 UTC" → drop the zone name
      [[ "$ts" -lt "$CUTOFF" ]] || continue
      say "  $([[ $GO -eq 1 ]] && echo rm || echo would)   image $repo (${id:7:12}, created ${created%% *})"
      if [[ $GO -eq 1 ]]; then
        docker image rm "$id" >/dev/null 2>&1 || say "         (in use or multi-tagged — left alone)"
      fi
    done

say ""
say "== TIER 2 — Max said yes on 2026-09-17: dominated or unreferenced, all re-downloadable =="
rm_path ~/hf_models "safetensors source checkpoints (Qwen3.5-2B/4B/9B, SocratTeachLLM, glm-4-9b)"
rm_path "$W/SocratTeachLLM-Q8_0.gguf"  "no serve script references it"
rm_path "$W/glm-4-9b-chat-Q8_0.gguf"   "no serve script references it"
say "  -- Phase D: catalog models the current default dominates (./scripts/fetch-weight.sh <name> brings any back) --"
rm_path "$W/Qwen3.6-27B-uncensored-heretic-v2-Native-MTP-Preserved-Q5_K_M.gguf" "Heretic v2 Q5 — displaced as default 2026-08-19"
rm_path "$W/Qwen3.6-27B-MTP-UD-Q5_K_XL.gguf" "Qwen3.6 27B MTP Q5 — the NON-MTP sibling is the campaign's champion and is KEPT"
rm_path "$W/Qwen3.8-27B-Q6_K.gguf"           "Qwen3.8 27B Q6_K — same model as the Q5 default, slower, 3 GB more"

if [[ $FLASH -eq 1 ]]; then
  say ""
  say "== --flash-next: the 177B MoE, shelved 2026-09-11 (38 tok/s, lost to the dense 27B on quality AND speed) =="
  for f in "$W"/Qwen3.8-Flash-Next-Uncensored-*.gguf; do rm_path "$f" "Flash-Next (support PR #60 stays; fetch-weight re-downloads)"; done
else
  say ""
  say "  (not included: Qwen3.8-Flash-Next, 96 GB, shelved as too slow — add --flash-next if you are done with it)"
fi

if [[ $SUDO -eq 1 ]]; then
  say ""
  say "== --sudo: system caches =="
  if command -v paccache >/dev/null 2>&1; then
    if [[ $GO -eq 1 ]]; then sudo paccache -rk2; else paccache -dk2 2>/dev/null | tail -n2; fi
  else
    say "  paccache missing — sudo pacman -S pacman-contrib, then re-run (keeps the last 2 versions of every package, so the kernel rollback stays)"
  fi
  say "  coredumps (7 GB — the waybar crash of 09-15 is in there; both upstream issues are already filed):"
  if [[ $GO -eq 1 ]]; then sudo journalctl --vacuum-size=200M >/dev/null 2>&1; sudo rm -f /var/lib/systemd/coredump/*; say "  removed"; else sudo -n true 2>/dev/null && sudo du -sh /var/lib/systemd/coredump || du -sh /var/lib/systemd/coredump 2>/dev/null; fi
else
  say ""
  say "  (not included: /var/cache/pacman/pkg 35 GB and /var/lib/systemd/coredump 7 GB — add --sudo)"
fi

say ""
printf '== %s: %.0f GB in files' "$([[ $GO -eq 1 ]] && echo FREED || echo 'DRY RUN — would free')" "$(awk -v k="$TOTAL_KB" 'BEGIN{print k/1048576}')"
say " (+ ~25 GB docker build cache$([[ $SUDO -eq 1 ]] && echo ', + pacman/coredumps'))"
[[ $GO -eq 1 ]] || say "   Nothing was deleted. Re-run with --go."
df -h /home | tail -n1
