#!/bin/bash
# =============================================================================
# Disk prune — 2026-09-17. Re-audited today against scratch/DISK-PRUNE-PLAN-
# 2026-09-11.md (the Trash is already empty; sizes below are today's).
#
#   bash scratch/prune-2026-09-17.sh            # DRY RUN: prints what and how much
#   bash scratch/prune-2026-09-17.sh --go       # does tiers 1 + 2 (no sudo needed)
#   bash scratch/prune-2026-09-17.sh --go --sudo         # + pacman cache, coredumps
#   bash scratch/prune-2026-09-17.sh --go --flash-next   # + the shelved 177B MoE (96 GB)
#
# SAFE TO RUN WHILE THE CAMPAIGN IS MEASURING: everything here is `rm` of cold
# files under ionice/nice — no builds, no GPU, nothing the campaign reads. The
# KEEP guard below refuses any weight a serve script in use, the campaign, or a
# live llama-server names, whatever the lists say.
#
# NEVER TOUCHED, on purpose:
#   * docker VOLUMES — the stack is down, so Open WebUI's data volume (your
#     chats and users) counts as "unused" right now. The old plan's
#     `docker system prune -a --volumes` would have been a bad day.
#   * research artifacts (research/lowrank/**, weights/research-staging/**):
#     that tier is OFFLOAD-to-external-drive, not delete — GPU-hours live there,
#     and stage F reads the IQ2 pair + BF16 this week.
#   * ~/Documents/scu, ~/Documents/projects — coursework, not mine to judge.
# =============================================================================
set -uo pipefail
GO=0; SUDO=0; FLASH=0
for a in "$@"; do
  case "$a" in
    --go) GO=1 ;; --sudo) SUDO=1 ;; --flash-next) FLASH=1 ;;
    -h|--help) sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done
OB=/home/max/Documents/openbeast
W="$OB/weights"
TOTAL_KB=0
say() { printf '%s\n' "$*"; }

# ---- KEEP guard: weights something still needs --------------------------------
KEEP="$( {
  # the default, the last-started and the bootstrap serve scripts
  for s in "$OB"/scripts/serve-qwen38-27b-uncensored-mtp-q5.sh \
           "$OB/scripts/$(head -n1 "$OB/.run/serve-script" 2>/dev/null || echo none)" \
           "$OB"/scripts/serve-bootstrap.sh \
           "$OB"/scripts/serve-qwen-27b-q5.sh "$OB"/scripts/serve-qwen38-27b-uncensored-q5.sh; do
    [[ -f "$s" ]] && grep -ho '[A-Za-z0-9._-]*\.gguf' "$s"
  done
  # everything the running campaign's scripts name
  grep -ho '[A-Za-z0-9._-]*\.gguf' "$OB"/scratch/campaign_master3.sh "$OB"/scratch/tier3_zig_ab.sh \
       "$OB"/scratch/greedy_floor.sh "$OB"/scratch/e32_capability3.sh 2>/dev/null
  # anything a live llama-server has open
  for p in $(pgrep -x llama-server 2>/dev/null); do
    ls -l "/proc/$p/fd" 2>/dev/null | grep -o '[A-Za-z0-9._-]*\.gguf'
  done
} | sort -u )"

kb_of() { ionice -c3 nice -n19 du -sk "$1" 2>/dev/null | awk '{print $1}'; }

rm_path() {                       # rm_path <path> <why>
  local p="$1" why="$2" kb base
  [[ -e "$p" || -L "$p" ]] || return 0
  base="$(basename "$p")"
  if [[ "$base" == *.gguf ]] && grep -qxF "$base" <<< "$KEEP"; then
    say "  KEEP   $p — still named by a serve script / the campaign / a live server"
    return 0
  fi
  kb="$(kb_of "$p")"; kb="${kb:-0}"
  TOTAL_KB=$((TOTAL_KB + kb))
  printf '  %-6s %6.1f GB  %s\n         %s\n' "$([[ $GO -eq 1 ]] && echo rm || echo would)" \
         "$(awk -v k="$kb" 'BEGIN{print k/1048576}')" "$p" "$why"
  [[ $GO -eq 1 ]] && ionice -c3 nice -n19 rm -rf -- "$p"
  return 0
}

say "== TIER 1 — caches and leftovers: re-created on demand, zero decisions =="
rm_path ~/.cache/uv        "uv package cache"
rm_path ~/.cache/pip       "pip cache"
rm_path ~/.cache/pypoetry  "poetry cache"
rm_path ~/Downloads/ubuntu-26.04-desktop-amd64.iso "an installer ISO"
# HF hub cache: old NLP-course models + a dataset. Qwen3.5-0.8B-Base stays —
# the E16 0.8B experiment is ACTIVE and may re-read it.
for d in ~/.cache/huggingface/hub/*; do
  case "$(basename "$d")" in
    models--Qwen--Qwen3.5-0.8B-Base|version.txt|.locks) ;;
    *) rm_path "$d" "HF hub cache (re-downloadable)" ;;
  esac
done
rm_path ~/.cache/huggingface/datasets "HF datasets cache — derived Arrow files from NLP coursework; regenerated by re-running the notebook that made them"
# The two feature worktrees: #61 and #62 were squash-merged; both trees are clean.
for wt in /home/max/Documents/openbeast-artifact /home/max/Documents/openbeast-chat; do
  if [[ -d "$wt" ]]; then
    if [[ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]]; then
      say "  KEEP   $wt — it has uncommitted changes"
    else
      kb="$(kb_of "$wt")"; TOTAL_KB=$((TOTAL_KB + ${kb:-0}))
      say "  $([[ $GO -eq 1 ]] && echo rm || echo would)   worktree $wt (squash-merged; branch itself is kept)"
      [[ $GO -eq 1 ]] && git -C "$OB" worktree remove "$wt"
    fi
  fi
done
say ""
say "  docker: build cache + images/containers from projects untouched for 90+ days"
say "          (NOT volumes, NOT open-webui/searxng — see the header)"
if [[ $GO -eq 1 ]]; then
  docker builder prune -af 2>/dev/null | tail -n1
  docker container prune -f --filter "until=2160h" 2>/dev/null | tail -n1
  docker image prune -af --filter "until=2160h" 2>/dev/null | tail -n1
else
  docker system df 2>/dev/null | awk 'NR==1 || /Build Cache|Images/'
fi

say ""
say "== TIER 2 — Max said yes on 2026-09-17: dominated or unreferenced, all re-downloadable =="
rm_path ~/hf_models "safetensors source checkpoints (Qwen3.5-2B/4B/9B, SocratTeachLLM, glm-4-9b)"
rm_path "$W/SocratTeachLLM-Q8_0.gguf"  "no serve script references it"
rm_path "$W/glm-4-9b-chat-Q8_0.gguf"   "no serve script references it"
say "  -- Phase D: catalog models the current default dominates (./scripts/fetch-weight.sh <name> brings any back) --"
rm_path "$W/Qwen3.6-27B-uncensored-heretic-v2-Native-MTP-Preserved-Q5_K_M.gguf" "Heretic v2 Q5 — displaced as default 2026-08-19"
rm_path "$W/Qwen3.6-27B-MTP-UD-Q5_K_XL.gguf" "Qwen3.6 27B MTP Q5 — the NON-MTP sibling is the campaign's champion and is KEPT"
rm_path "$W/Qwen3.8-27B-Q6_K.gguf"           "Qwen3.8 27B Q6_K — same model as the Q5 default, slower, 3 GB more"

if [[ $FLASH -eq 1 ]]; then
  say ""
  say "== --flash-next: the 177B MoE, shelved 2026-09-11 (38 tok/s, lost to the dense 27B on quality AND speed) =="
  for f in "$W"/Qwen3.8-Flash-Next-Uncensored-*.gguf; do rm_path "$f" "Flash-Next (support PR #60 stays; fetch-weight re-downloads)"; done
else
  say ""
  say "  (not included: Qwen3.8-Flash-Next, 96 GB, shelved as too slow — add --flash-next if you are done with it)"
fi

if [[ $SUDO -eq 1 ]]; then
  say ""
  say "== --sudo: system caches =="
  if command -v paccache >/dev/null 2>&1; then
    if [[ $GO -eq 1 ]]; then sudo paccache -rk2; else paccache -dk2 2>/dev/null | tail -n2; fi
  else
    say "  paccache missing — sudo pacman -S pacman-contrib, then re-run (keeps the last 2 versions of every package, so the kernel rollback stays)"
  fi
  say "  coredumps (7 GB — the waybar crash of 09-15 is in there; both upstream issues are already filed):"
  if [[ $GO -eq 1 ]]; then sudo journalctl --vacuum-size=200M >/dev/null 2>&1; sudo rm -f /var/lib/systemd/coredump/*; say "  removed"; else sudo -n true 2>/dev/null && sudo du -sh /var/lib/systemd/coredump || du -sh /var/lib/systemd/coredump 2>/dev/null; fi
else
  say ""
  say "  (not included: /var/cache/pacman/pkg 35 GB and /var/lib/systemd/coredump 7 GB — add --sudo)"
fi

say ""
printf '== %s: %.0f GB in files' "$([[ $GO -eq 1 ]] && echo FREED || echo 'DRY RUN — would free')" "$(awk -v k="$TOTAL_KB" 'BEGIN{print k/1048576}')"
say " (+ ~25 GB docker build cache$([[ $SUDO -eq 1 ]] && echo ', + pacman/coredumps'))"
[[ $GO -eq 1 ]] || say "   Nothing was deleted. Re-run with --go."
df -h /home | tail -n1
